[package]
name = "eie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linreg = "0.2.0"
log = "0.4.17"

[dev-dependencies]
csv = "1.2"
serde = { version = "1.0.159", features = ["derive"] }